[package]
name = "qrmethis"
version = "0.1.0"
authors = ["Mike Moran <mike@houseofmoran.com>"]
edition = "2018"

[dependencies.qrcode]
version = "0.10.0"

[dependencies.image]
version = "0.21.1"

[dependencies]
rocket = "0.4.0"
juniper = "0.11.1"
juniper_rocket = "0.2.0"
url = "1.7.2"